//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyNhaSachEntities : DbContext
    {
        public QuanLyNhaSachEntities()
            : base("name=QuanLyNhaSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiSach> LoaiSaches { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhaXuatBan> NhaXuatBans { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
    
        public virtual ObjectResult<Pro_ThongKeDoanhThuTheoThang_Result> Pro_ThongKeDoanhThuTheoThang(Nullable<int> month)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_ThongKeDoanhThuTheoThang_Result>("Pro_ThongKeDoanhThuTheoThang", monthParameter);
        }
    
        public virtual ObjectResult<Pro_ThongKeDSTungThang_Result> Pro_ThongKeDSTungThang(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_ThongKeDSTungThang_Result>("Pro_ThongKeDSTungThang", yearParameter);
        }
    
        public virtual ObjectResult<Pro_BestSales_Result> Pro_BestSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_BestSales_Result>("Pro_BestSales");
        }
    
        public virtual ObjectResult<Pro_BestSalesByMonth_Result> Pro_BestSalesByMonth(Nullable<int> month)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_BestSalesByMonth_Result>("Pro_BestSalesByMonth", monthParameter);
        }
    }
}
